ARG EC2_HOST
ENV EC2_HOST=${EC2_HOST}

ARG PSQL_PORT
ENV PSQL_PORT=${PSQL_PORT}

ARG PSQL_DATABASE
ENV PSQL_DATABASE=${PSQL_DATABASE}

ARG PSQL_USERNAME
ENV PSQL_USERNAME=${PSQL_USERNAME}

ARG PSQL_PASSWORD
ENV PSQL_PASSWORD=${PSQL_PASSWORD}

ARG REDIS_PORT
ENV REDIS_PORT=${REDIS_PORT}

ARG JWT_SECRET
ENV JWT_SECRET=${JWT_SECRET}

ARG AWS_ACCESS_KEY
ENV AWS_ACCESS_KEY=${AWS_ACCESS_KEY}

ARG AWS_SECRET_KEY
ENV AWS_SECRET_KEY=${AWS_SECRET_KEY}

ARG AWS_BUCKET_NAME
ENV AWS_BUCKET_NAME=${AWS_BUCKET_NAME}

ARG AWS_REGION
ENV AWS_REGION=${AWS_REGION}

ARG KAKAO_CLIENT_ID
ENV KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}

ARG KAKAO_CLIENT_SECRET
ENV KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}

ARG NAVER_CLIENT_ID
ENV NAVER_CLIENT_ID=${NAVER_CLIENT_ID}

ARG NAVER_CLIENT_SECRET
ENV NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}

# 빌드 할 때에는 jdk 17버전을 사용하겠다.
FROM eclipse-temurin:17-jdk AS build

# 작업 디렉토리 설정
WORKDIR /app

# 프로젝트 루트에 있는 파일을 컨테이너 안으로 복사해서 넣기
COPY . .

# 빌드
RUN chmod +x ./gradlew && ./gradlew build

# 실행만 담당하는 jre 환경으로 설정한다.
FROM eclipse-temurin:17-jre

ENV TZ=Asia/Seoul

# JAR 파일 복사
COPY /app/build/libs/app-0.0.1-SNAPSHOT.jar app.jar

# 포트 오픈
EXPOSE 10000

# 실행 명령어
ENTRYPOINT ["java", "-jar", "app.jar"]














