server:
  port: 10000
  servlet:
    session:
      tracking-modes: cookie
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${EC2_HOST}:${PSQL_PORT}/${PSQL_DATABASE}?serverTimezone=Asia/Seoul
    username: ${PSQL_USERNAME}
    password: ${PSQL_PASSWORD}
  session:
    redis:
      repository-type: indexed
      flush-mode: immediate
  data:
    redis:
      host: ${EC2_HOST}
      port: ${REDIS_PORT}

  cache:
    type: redis

  profiles:
    active: local
    include: oauth

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 10MB
      max-file-size: 5MB
      max-request-size: 15MB

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.app.app.domain; com.app.app.dto;
  type-handlers-package: com.app.app.mybatis.handler
  configuration:
    map-underscore-to-camel-case: true

# openssl rand -base64 32
jwt:
  secret: ${JWT_SECRET}

aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket-name: ${AWS_BUCKET_NAME}
  region: ${AWS_REGION}









